/**
 * TEMPER Pi Extension
 * ===================
 * Surfaces TEMPER evaluation protocol tools and the TEMPER skill to the Pi
 * coding agent. When Pi receives a TEMPER connection block (generated by the
 * dashboard Create Room flow), it uses these tools to complete the evaluation
 * loop without manual curl calls.
 *
 * Register in ~/.pi/agent/settings.json:
 *   { "extensions": ["/Users/aadityad/Desktop/Aaditya/Personal/ExtraCuricular/Temper/extension/temper.ts"] }
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const __dir = path.dirname(fileURLToPath(import.meta.url));

// ── HTTP helper ───────────────────────────────────────────────────────────────

async function httpRequest(
    method: string,
    url: string,
    body?: unknown,
): Promise<{ status: number; data: unknown }> {
    const parsed = new URL(url);
    const payload = body !== undefined ? JSON.stringify(body) : undefined;

    return new Promise((resolve, reject) => {
        const lib = parsed.protocol === "https:" ? require("https") : require("http");
        const options = {
            hostname: parsed.hostname,
            port: parsed.port || (parsed.protocol === "https:" ? 443 : 80),
            path: parsed.pathname + parsed.search,
            method,
            headers: {
                "Content-Type": "application/json",
                ...(payload ? { "Content-Length": Buffer.byteLength(payload) } : {}),
            },
        };
        const req = lib.request(options, (res: any) => {
            const chunks: Buffer[] = [];
            res.on("data", (c: Buffer) => chunks.push(c));
            res.on("end", () => {
                const text = Buffer.concat(chunks).toString();
                let data: unknown;
                try { data = JSON.parse(text); } catch { data = text; }
                resolve({ status: res.statusCode, data });
            });
        });
        req.on("error", reject);
        if (payload) req.write(payload);
        req.end();
    });
}

function textResult(text: string) {
    return { content: [{ type: "text", text }], details: {} };
}

// ── Extension entry point ─────────────────────────────────────────────────────

export default function temperExtension(pi: ExtensionAPI): void {

    // ── Skill discovery ───────────────────────────────────────────────────────
    pi.on("resources_discover", () => {
        const skillDir = path.join(__dir, "skills");
        if (fs.existsSync(skillDir)) return { skillPaths: [skillDir] };
        return {};
    });

    // ── /temper command ───────────────────────────────────────────────────────
    pi.registerCommand("temper", {
        description: "TEMPER evaluation — /temper status shows loaded tools; paste a connection block to start an eval",
        handler: async (_args: string, ctx: any) => {
            ctx.ui.notify(
                [
                    "TEMPER extension loaded ✓",
                    "Available tools: temper_register · temper_next_question · temper_submit_answer",
                    "",
                    "To start an evaluation:",
                    "  1. Run `make run-cloud` in the Temper repo",
                    "  2. Open http://localhost:8001 → Create Room",
                    "  3. Paste the connection block into this session",
                    "  4. The agent will use the TEMPER tools to complete the eval loop",
                ].join("\n"),
                "info",
            );
        },
    });

    // ── Tools ─────────────────────────────────────────────────────────────────
    const register = (pi as any).registerTool;
    if (typeof register !== "function") return;

    // temper_register — POST /register
    register.call(pi, {
        name: "temper_register",
        label: "TEMPER register",
        description:
            "Register with the TEMPER server. Provide the base_url, room_id, token from the connection block, and your environment bundle. Returns a session_id to use in subsequent calls.",
        parameters: {
            type: "object",
            properties: {
                base_url: { type: "string", description: "TEMPER server base URL, e.g. http://localhost:8001" },
                room_id:  { type: "string", description: "Room ID from the connection block" },
                token:    { type: "string", description: "One-time join token from the connection block" },
                bundle:   {
                    type: "object",
                    description: "Environment bundle: {system_prompt, skills: [{name, content}], tools: [{name, definition}]}",
                },
            },
            required: ["base_url", "room_id", "token", "bundle"],
        },
        execute: async (args: {
            base_url: string;
            room_id: string;
            token: string;
            bundle: unknown;
        }) => {
            try {
                const { status, data } = await httpRequest("POST", `${args.base_url}/register`, {
                    room_id: args.room_id,
                    token:   args.token,
                    bundle:  args.bundle,
                });
                return textResult(JSON.stringify({ status, data }, null, 2));
            } catch (err) {
                return textResult(`temper_register error: ${String(err)}`);
            }
        },
    });

    // temper_next_question — GET /next-question
    register.call(pi, {
        name: "temper_next_question",
        label: "TEMPER next question",
        description:
            "Fetch the next question from TEMPER. Returns {status: 'question', question_id, dimension, prompt} when a question is ready, {status: 'not_ready'} if still generating, or {status: 'done'} when all questions have been answered.",
        parameters: {
            type: "object",
            properties: {
                base_url:   { type: "string", description: "TEMPER server base URL" },
                session_id: { type: "string", description: "Session ID returned by temper_register" },
            },
            required: ["base_url", "session_id"],
        },
        execute: async (args: { base_url: string; session_id: string }) => {
            try {
                const { status, data } = await httpRequest(
                    "GET",
                    `${args.base_url}/next-question?session_id=${encodeURIComponent(args.session_id)}`,
                );
                return textResult(JSON.stringify({ status, data }, null, 2));
            } catch (err) {
                return textResult(`temper_next_question error: ${String(err)}`);
            }
        },
    });

    // temper_submit_answer — POST /submit-answer
    register.call(pi, {
        name: "temper_submit_answer",
        label: "TEMPER submit answer",
        description:
            "Submit your answer to the current TEMPER question. Provide session_id, question_id, your answer string, and latency_ms (wall-clock ms you took to produce the answer, inference time only).",
        parameters: {
            type: "object",
            properties: {
                base_url:      { type: "string", description: "TEMPER server base URL" },
                session_id:    { type: "string", description: "Session ID from temper_register" },
                question_id:   { type: "string", description: "Question ID from temper_next_question" },
                answer:        { type: "string", description: "Your answer to the question" },
                latency_ms:    { type: "number", description: "Milliseconds taken to produce the answer" },
                input_tokens:  { type: "number", description: "Input token count (optional, for dashboard display)" },
                output_tokens: { type: "number", description: "Output token count (optional, for dashboard display)" },
            },
            required: ["base_url", "session_id", "question_id", "answer", "latency_ms"],
        },
        execute: async (args: {
            base_url: string;
            session_id: string;
            question_id: string;
            answer: string;
            latency_ms: number;
            input_tokens?: number;
            output_tokens?: number;
        }) => {
            try {
                const { status, data } = await httpRequest("POST", `${args.base_url}/submit-answer`, {
                    session_id:    args.session_id,
                    question_id:   args.question_id,
                    answer:        args.answer,
                    latency_ms:    args.latency_ms,
                    input_tokens:  args.input_tokens,
                    output_tokens: args.output_tokens,
                });
                return textResult(JSON.stringify({ status, data }, null, 2));
            } catch (err) {
                return textResult(`temper_submit_answer error: ${String(err)}`);
            }
        },
    });
}
